config/routes.rb
OrgManagement::Application.routes.draw do
  resources :user_organizations

  resources :users_organizations

  devise_for :users
  resources :organizations

  root 'organizations#index'

  

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :child_organizations, class_name: "Organization", foreign_key: "parent_organization_id"
  belongs_to :parent_organization, class_name: "Organization"
  
  has_many :user_organizations
  has_many :users, :through => :user_organizations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_organizations
  has_many :organizations, :through => :user_organizations
  
  scope :privileged, lambda{|org| organizations.include?(org)}
  
end

app/models/user_organization.rb
class UserOrganization < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :get_all_organizations

  # GET /organizations
  # GET /organizations.json
  def index
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end
    
    def get_all_organizations
      @organizations = Organization.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :employee_size, :since, :location, :zip, :phone, :email, :parent_organization_id)
    end
end

app/controllers/user_organizations_controller.rb
class UserOrganizationsController < ApplicationController
  before_action :set_user_organization, only: [:show, :edit, :update, :destroy]
  before_filter :get_all_data

  # GET /user_organizations
  # GET /user_organizations.json
  def index
    @user_organizations = UserOrganization.all
  end

  # GET /user_organizations/1
  # GET /user_organizations/1.json
  def show
  end

  # GET /user_organizations/new
  def new
    @user_organization = UserOrganization.new
  end

  # GET /user_organizations/1/edit
  def edit
  end

  # POST /user_organizations
  # POST /user_organizations.json
  def create
    @user_organization = UserOrganization.new(user_organization_params)
    
    org_ids = extract_org_ids
    
    respond_to do |format|
      org_ids.values.each do |org_id|
        @user_organization.organization_id = org_id
        if @user_organization.save
          format.html { redirect_to @user_organization, notice: 'Users organization was successfully created.' }
          format.json { render action: 'index', status: :created, location: @user_organizations }
        else
          format.html { render action: 'new' }
          format.json { render json: @user_organization.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /user_organizations/1
  # PATCH/PUT /user_organizations/1.json
  def update
    org_ids = extract_org_ids
    org_user = UserOrganization.find_by_user_id(params[:user_organization][:user_id])
    if org_user.present?
      org_user.delete
      @user_organization = UserOrganization.new
    end
    respond_to do |format|
      org_ids.values.each do |org_id|
        @user_organization.organization_id = org_id
        if @user_organization.update_attributes(user_organization_params)
          format.html { redirect_to :action => :index, notice: 'Users organization was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user_organization.errors, status: :unprocessable_entity }
        end
       end
    end
  end

  # DELETE /user_organizations/1
  # DELETE /user_organizations/1.json
  def destroy
    @user_organization.destroy
    respond_to do |format|
      format.html { redirect_to user_organizations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_organization
      @user_organization = UserOrganization.find(params[:id])
    end
    
    def extract_org_ids
      org_ids = params.select{|key,value| key.match(/^org_id\d+/)}
    end
    
    def get_all_data
      @users = User.all
      @organizations = Organization.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_organization_params
      params.require(:user_organization).permit(:organization_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/user_organizations_helper.rb
module UserOrganizationsHelper
end

app/helpers/users_organizations_helper.rb
module UsersOrganizationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>OrgManagement</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<% if notice %>
		<p class="alert alert-success">
			<%= notice %>
		</p>
		<% end %>
		<% if alert %>
		<p class="alert alert-danger">
			<%= alert %>
		</p>
		<% end %>

		<p class="navbar-text pull-right">
			<% if user_signed_in? %>
			Logged in as <strong><%= current_user.email %></strong>.
			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
			<% else %>
			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
			<% end %>

			<%= yield %>

	</body>
</html>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :employee_size %><br>
    <%= f.text_field :employee_size %>
  </div>
  <div class="field">
    <%= f.label :since %><br>
    <%= f.datetime_select :since %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :parent_organization %><br>
    <%= f.select :parent_organization_id, @organizations.map{|org| [org.name, org.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Employee size</th>
      <th>Since</th>
      <th>Location</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
    	<% if current_user.organizations.include?(organization)%>
	      <tr>
	        <td><%= organization.name %></td>
	        <td><%= organization.employee_size %></td>
	        <td><%= organization.since %></td>
	        <td><%= organization.location %></td>
	        <td><%= organization.zip %></td>
	        <td><%= organization.phone %></td>
	        <td><%= organization.email %></td>
	        <td><%= link_to 'Show', organization %></td>
	        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
	        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
		<% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Employee size:</strong>
  <%= @organization.employee_size %>
</p>

<p>
  <strong>Since:</strong>
  <%= @organization.since %>
</p>

<p>
  <strong>Location:</strong>
  <%= @organization.location %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @organization.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organization.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organization.email %>
</p>

<p>
  <strong>Parent Organization:</strong>
  <%= @organization.parent_organization.name %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/user_organizations/_form.html.erb
<%= form_for(@user_organization) do |f| %>
  <% if @user_organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_organization.errors.count, "error") %> prohibited this user_organization from being saved:</h2>

      <ul>
      <% @user_organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.select :user_id, @users.map{|user| [user.email, user.id]}, :selected => @user_organization.user.id %>
  </div>
  <div class="field">
    Check the organizations you would want to give the user access to:<br>
    <% @organizations.each do |org|%>
    	<%= org.name %>
    	<%= check_box_tag "org_id"+"#{org.id}", "#{org.id}"%><br>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_organizations/edit.html.erb
<h1>Editing user_organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_organization %> |
<%= link_to 'Back', user_organizations_path %>

app/views/user_organizations/index.html.erb
<h1>Listing user_organizations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Organization</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_organizations.each do |user_organization| %>
      <tr>
        <td><%= user_organization.user.email %></td>
        <td><%= user_organization.organization.name %></td>
        <td><%= link_to 'Show', user_organization %></td>
        <td><%= link_to 'Edit', edit_user_organization_path(user_organization) %></td>
        <td><%= link_to 'Destroy', user_organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User organization', new_user_organization_path %>

app/views/user_organizations/new.html.erb
<h1>New user_organization</h1>

<%= render 'form' %>

<%= link_to 'Back', user_organizations_path %>

app/views/user_organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_organization.user.email %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @user_organization.organization.name %>
</p>

<%= link_to 'Edit', edit_user_organization_path(@user_organization) %> |
<%= link_to 'Back', user_organizations_path %>